#+AUTHOR: Yuuhi
#+TITLE: ４月の記録１
#+LANGUAGE: ja
#+HTML: <meta content='no-cache' http-equiv='Pragma' />
#+STYLE: <link rel="stylesheet" type="text/css" href="./org-mode.css">

* 1日
うわあああああああ
** A Normal Formとは

* 2日
** 英文法
- 時制
  - 現在形
  - 進行形
  - 現在形の特殊な用法
  - 現在完了形

- 仮定法
  - 見抜き方
  - 倒置

- 助動詞
  - will
  - 代用表現
  - may

- 不定詞
  - 未来

- 動名詞

- 分詞構文
* 3日
* 4日
* 5日
** Emacsのフォントサイズ変更
"C-x C-+"と"C-x C--"でフォントサイズを変更できる

* 6日
進捗を書かないと迷走する．何かやったつもりで時間が過ぎる
- 何をやるか決めてから，作業を始める
- 本を読むときは区切りまで読んだら感想を書く

** やりたいこととやらないといけないことのまとめ
- 大学でのこと
  - 変換器を書く
  - 論文読む
    - 論文よんだらまとめる
  - 進捗資料をまとめる
    - プレゼンをbeamerで作る
  - セマンティックのことを理解する
  - Haskellの勉強をする
  - 並行処理(コルーチン)のことを調べてまとめる

- その他
  - Androidアプリケーションの設計と実装
    - Twitterクライアント
    - ゲーム
  - GracemonkeyのJSの書き方を覚える
  - Firefox Extensionを作る
    - 情報収集のためのスクリプト
  - クロールのツール作り
  - Luaのことを調べる
  - TODO TOEICの勉強
  - SQLの勉強(MySQLを自鯖で本格運用する)

読んだらまとめる．
作る前にまとめる．

* 7日
** アイデア
- 非実在魔法少女研究会うねうね
- うねうねのこと
  - うねうねってなに？
  - 入会希望の場合
  - 活動日
  - アクセス
  - 研究会規則
  - 連絡先
- メンバー紹介
- イベント
  - 新入生歓迎会
  - スキー合宿
- 作品紹介
- 研究会ログ
- ゲームレビュー
- 読書感想

* 8日
うむ

* 9日
** CSS弄った
- 文字 #dfdfdf
- 背景 #404743
が基本で

** 数学記号(UNICODE)
#+begin_src ruby -n
(0x2200..0x22AF).each { |x|
  print [x].pack("U")
}
#+end_src
- 結果
∀∁∂∃∄∅∆∇∈∉∊∋∌∍∎∏∐∑−∓∔∕∖∗∘∙√∛∜∝∞∟∠∡∢∣∤∥∦∧∨∩∪∫∬∭∮∯∰∱∲∳∴∵∶∷∸∹
∺∻∼∽∾∿≀≁≂≃≄≅≆≇≈≉≊≋≌≍≎≏≐≑≒≓≔≕≖≗≘≙≚≛≜≝≞≟≠≡≢≣≤≥≦≧≨≩≪≫≬≭≮≯≰≱≲≳≴≵≶≷≸≹≺≻≼≽≾≿
⊀⊁⊂⊃⊄⊅⊆⊇⊈⊉⊊⊋⊌⊍⊎⊏⊐⊑⊒⊓⊔⊕⊖⊗⊘⊙⊚⊛⊜⊝⊞⊟⊠⊡⊢⊣⊤⊥⊦⊧⊨⊩⊪⊫⊬⊭⊮⊯

** AA貼るテスト
#+begin_example
　　　　　 / ￣＼
　　 　 γ"⌒ ヽ ＼＿ノ
　　　　i　ｌ!从ﾉﾘ）　
　　　　| リﾟ ヮﾟﾉﾘ　 れっつにゃー！
　　　 / ﾉ○卯つ
　　／// ゝ　>|ゝヽ
　〃/ﾚﾙ’イ_/ ヽヽヽ
#+end_example

#+begin_example
　　　　 　l^丶
　　　　　 | 　'ﾞ''"'''ﾞ y-―, あ　ふんぐるい　むぐるうなふ　くとぅるう
　　　　　 ﾐ　´ ∀ ｀　　,:'　
　　　　(丶　　　　(丶 ミ　　　いあ　　 　いあ
（（　 　 ﾐ　　　　　　　 ;':　　ﾊ,_,ﾊ 　　ﾊ,_,ﾊ
　　　　　;:　　　　　　 　ﾐ 　';´∀｀'; 　';´∀｀';, ,
　　　　　`:; 　　　　　　,:'　　ｃ　 ｃ.ﾐ'　ｃ　 ｃ.ﾐ
　　　　　　U"ﾞ'''~"＾'丶)　　　u''ﾞ"J 　 u''ﾞ"J


　　　　　　　　　 /^l
　　 ,―-y'"'~"ﾞ´　 |それ　 るるいえ　うがふなぐる　ふたぐん
　　 ヽ　　´ ∀ ｀　 ﾞ':
　　　ﾐ　　.,/)　　　､/) 　　　いあ　　　　いあ
　　　ﾞ,　　 "'　　　´''ﾐ　　　ﾊ,_,ﾊ 　　　ﾊ,_,ﾊ
（（　 ミ　　　　　　　;:'　　,:' ´∀｀';　　,:' ´∀｀';
　　　 ';　　　　　　彡　　::　っ　,っ　 ::　っ　,っ
　　　　(/~"ﾞ''´~"U 　　 ι''"ﾞ''u 　ι''"ﾞ''u 
#+end_example

** 手持ちのMacBookAirのLionでX11アプリケーションが動かない
- 多分以前にRabbitとかmikutterを動かそうとした時にいろいろ弄ってダメにしたような気がするｗｗ
  - 修復の仕方は検討がつかないため，X11アプリケーションを使うことを諦める方向で．．\_(º﹃º｣ ∠)_


** ruby-modeのこと
[C-c C-s]でirb起動，[C-c C-r]で選択範囲の評価．

** ネットワークのこと
「ネットワークはなぜつながるか」戸根 勤(著)などを読んでネットワークの基礎を固める．
- Webブラウザからのメッセージ
  - HTTPリクエスト・メッセージ
  - WebサーバのIPアドレス
  - DNSサーバ
  - プロトコル・スタック
- TCP/IP
  - ソケット
  - サーバ接続
  - データの送受信
  - サーバ切断とソケット抹消
  - IPとイーサネットのパケット送受信
  - UDPプロトコル
- リピータ・ハブ
  - スイッチング・ハブ
  - ルータのパケット中継
  - ルータの機能
- 回線のこと
- サーバ側のLANのこと
  - Webサーバの設置
  - ファイアウォール
  - 負荷分散
  - キャッシュサーバ
  - 配信サービス
- Webサーバの概要
  - サーバ
  - 受信動作
  - レスポンスのこと



** org-mode
C-c C-o（org-open-at-point）でリンク開ける．
C-c &で戻る？

#+begin_example
［ ［*5日］］
#+end_example
で内部リンク

** TOEICの勉強は必須？
なのかどうかは正直分からんが，英語の読み書きは苦にならない程度にできないと，
資料もロクに読めないため
| 回数    | 開催日              | 結果発送            |
|---------+---------------------+---------------------|
| 第170回 | *2012年5月27日（日）* | 2012年6月26日（火） | 

*今度は寝坊しないように*

* 10日
** Standard ECMA-262読む
- ECMAScript Language Specification


** Androidのツイッタークライアント作り
Twitter4jを使ったUserStreamへの対応のが分かった．

- ここ
http://www.adakoda.com/adakoda/2011/08/android-twitter4j-userstream.html

- Adapterパターン早急に覚える
ListViewの操作のため

* 11日
#+begin_example
565 本当にあった怖い名無し :2007/10/20(土) 12:23:16 ID:ZlSlnPj40
私は慄然たる思いで机の引出しから突如現れたその異形の物体を凝視した。
それは大小の球体を組み合わせたとしか言い様の無い姿をしており、狂気じみた
青色が純白の顔と腹部を縁取っていた。這いずり回るような冒涜的な足音で私に
近付くと、何とも名状し難き声で私と私の子孫のおぞましき未来を語るのであった。
また、それは時空を超越した底知れぬ漆黒の深淵に通じる袋状の器官を有しており、
この世の物ならざる奇怪な装置を取り出しては、人々を混迷に陥れるのであった。
#+end_example

** Androidアプリ
ListViewで，一番上にスムーズにアイテムを追加する方法が分からん．
描画のタイミングの操作とか，notifyDataSetChangedメソッドを呼び出しても更新がすぐに反映されない問題．

* 12日
** Androidの歴史
2005年にGoogleがAndroid.Inc.というスタートアップを買収．
2008年にAndroid1.0がリリース．
Androidはオープンソース．
Android自体はLinuxカーネル2.6をベースとするオペレーティングシステム／プラットフォーム

** Android Twitter Client製作
US対応のListActivityでsmoothScrollToPositionメソッドを使うとtouchでのスクロールに難が出
ると思い込んでいたがそんなことはなかった．

- ListViewとListActivityと

ここの説明が一番良い感じ？
http://d.hatena.ne.jp/shimobayashi/20110319/1300516097

** TODO Adapterパターンのことをよく調べておく．

* 13日

** tmuxのショートカット
'Prefix [' でcopy-modeに移行
'Prefix C-Space'で選択範囲指定
'C-w'とかでコピー
'Prefix ]'でペースト

* 14日
 
** VM環境でのOpenSUSEのセットアップ
- 今回はKDEを選択
- http://download.opensuse.org/repositories/devel:/languages:/haskell/openSUSE_Factory/ をリポジトリに追加．
  Yastを使う．CUIからできたほうが良いので後から調べておく．
- 今回は http://download.opensuse.org/repositories/devel:/languages:/haskell/openSUSE_11.4/ をリポジトリに追加した．
何がちがう？

- mongoDBはバイナリ持ってきて展開するだけで使える
#+begin_example
mkdir /data/db
#+end_example
が必要．

** オフ
クロヤマさんと焼肉を食べた．
美少女だった．

* 15日
** バーニングシップフラクタル
- zn+1=(|Re{zn}|+i|Im{zn}|)2+C

- バーニングシップ・フラクタル
http://aquioux.net/blog/coding/study/%E3%83%90%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0%E3%82%B7%E3%83%83%E3%83%97%E3%83%BB%E3%83%95%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%AB/

- マンデルブロ集合のx,yを絶対値にするだけ
#+begin_src javascript -n
x = Math.abs(x);
y = Math.abs(y);
zx = x * x - y * y + a;
zy = 2 * x * y + b;
if(zx * zx + zy * zy > 4) break;
#+end_src

** JSFiddleのこと
- JSFIDDLEとは
#+begin_quote
JsFiddle is a playground for web developers, a tool which may be used in many ways. One
can use it as an online editor for snippets build from HTML, CSS and JavaScript. The
code can then be shared with others, embedded on a blog, etc. Using this approach, 
JavaScript developers can very easily isolate bugs. We aim to support all actively developed 
frameworks - it helps with testing compatibility. (full Interview)
#+end_quote
http://doc.jsfiddle.net/

JsFiddleはWeb開発者のための遊び場でツール．
HTML，CSS，JavaScriptを書いて，その描画結果を簡単に確認できる．

- JSFIDDLEのより詳しい使い方は以下に
http://tokkono.cute.coocan.jp/blog/slow/index.php/xhtmlcss/fun-with-jsfiddle/

- canvasが使えない？？？

** canvasのこと
-リファレンス
 http://www.html5.jp/canvas/ref.html

- canvasでフラクタルを描画する
 http://kray.jp/blog/html5-canvas/

再帰プログラムによるフラクタル描画は 
http://codezine.jp/article/detail/73
でわかりやすく説明されている．

# - 簡単な例としてコッホ曲線

* 16日
** Portalというゲームが面白そう
パズルゲーム？

** zypperのこと
- zypper
http://en.opensuse.org/Zypper

- コマンドの説明
http://en.opensuse.org/Zypper/Usage http://ja.opensuse.org/Zypper/Usage/11.1

- チートシート
http://en.opensuse.org/Zypper/Usage#Cheat_sheet

** Yastの
パッケージリポジトリ 
http://ja.opensuse.org/%E8%BF%BD%E5%8A%A0%E3%81%AE_YaST_%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%83%BB%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA

** C++11の企画書が買える
http://d.hatena.ne.jp/faith_and_brave/20120413/1334298652

** MBAにXQuartz入れた．
もともと入っていたX11が動かなくなったので，Stable: 2.7.1 - 2012.02.20 をインストール．
 http://xquartz.macosforge.org/trac/wiki

動かない．X11を使うアプリケーションが使えなくなっているなぜだろう．．？

- 追記
.xinitrcの中身コメントアウトしたら動いた．おわり

** MBAでWindowsアプリケーションが動かしたい
miku installerですばひびは動いた．

** そういえば，Mac付属の辞書ってなんだっけ？
Mac OS X 10.5 からは「大辞泉(国語辞書)」、「プログレッシブ英和・和英中辞典」、「類語例
解辞典」、「Apple用語辞典」、「New Oxford American Dictionary(英英辞典)」、「Oxford Am
erican Writes's Thesaurus(英語類語辞典)」、「Wikipedia」が初期インストールされている．

** 小説家が着ていそうな防寒着
半纏

** OpenSUSEに素晴らしき日々インストールできない問題
- udfのファイルシステムのDVDがマウントできなかった
libudf0とudftoolsインストールして再起動したらマウントできたでござる

** TOEICの勉強しろ
ぐるるるるしろ！

** OpenSUSEでのmozcインストール方法
M17Nのリポジトリを追加する．
#+begin_quote
M17N は、多言語化: 多言語サポート関係のパッケージをアップデートします。 
#+end_quote
http://download.opensuse.org/repositories/M17N/openSUSE_11.4/

zypperでインストール．
インプットメソッドの設定の方法は後から調べる

** Tほげの申し込み
水曜昼までに！！！！
明日に必ず書類提出

** コッホ曲線
http://sorauta.bufsiz.jp/Fractal/koch.html

* 17日

* 18日
* 19day
** 変換規則を書くときのTeXの記述
http://www.latex-cmd.com/equation/transform.html#forier01
#+begin_example
\[
  G(f) = \mathcal{F}[g(t)]
\]
pre\[
  F(s) = \mathcal{L}[f(t)]
\]
#+end_example

* 20day
飲み会であった．
カラオケで歌って，その後麻雀をした．
人生で始めて国士無双を和了った．

* 21day

* 22day
** Ever17感想
- 最終ルートまでクリアした．
- 何を書いてもネタバレにつながりそう．
- 評価が高い理由は分かった気がする．
- 同じシナリオを何回も読まされるのは．．．
- 5年くらい前にやればのめり込めたと思う．
- スキップの遅さとかもあって，シナリオ中盤は無駄に時間を使わされる部分がある．

** さよ教ほしい


* 23day

